apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "${PROJECT_NAME}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "${PROJECT_NAME}"
  minReplicas: ${SCALE_MIN}
  maxReplicas: ${SCALE_MAX}
  metrics:
    - type: ContainerResource
      containerResource:
        name: memory
        container: "${PROJECT_NAME}"
        target:
          type: Utilization
          averageUtilization: 80
    - type: ContainerResource
      containerResource:
        name: cpu
        container: "${PROJECT_NAME}"
        target:
          type: Utilization
          averageUtilization: 80
