-- CreateTable
CREATE TABLE `HistoricalData` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `date` DATETIME(3) NOT NULL,
    `symbol` VARCHAR(191) NOT NULL,
    `priceHigh` DOUBLE NOT NULL,
    `priceLow` DOUBLE NOT NULL,
    `priceOpen` DOUBLE NOT NULL,
    `priceAverage` DOUBLE NOT NULL,
    `priceClose` DOUBLE NOT NULL,
    `totalVolume` INTEGER NOT NULL,
    `dealVolume` INTEGER NOT NULL,
    `putthroughVolume` INTEGER NOT NULL,
    `totalValue` BIGINT NOT NULL,
    `putthroughValue` INTEGER NOT NULL,
    `buyForeignQuantity` BIGINT NOT NULL,
    `buyForeignValue` BIGINT NOT NULL,
    `sellForeignQuantity` BIGINT NOT NULL,
    `sellForeignValue` BIGINT NOT NULL,
    `buyCount` BIGINT NOT NULL,
    `buyQuantity` BIGINT NOT NULL,
    `sellCount` BIGINT NOT NULL,
    `sellQuantity` BIGINT NOT NULL,
    `adjRatio` INTEGER NOT NULL,
    `currentForeignRoom` BIGINT NOT NULL,
    `propTradingNetDealValue` INTEGER NOT NULL,
    `propTradingNetPTValue` INTEGER NOT NULL,
    `propTradingNetValue` INTEGER NOT NULL,
    `unit` INTEGER NOT NULL,

    INDEX `HistoricalData_symbol_idx`(`symbol`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
